Feat/publisher addresses two feeds
PRX/feeder.prx.org pull request #479
Opened 2022-12-09 22:52 UTC by svevang

2022-12-14 21:26 UTC, cavis requested changes
One unnecessary hardcoding of the feed hosts (`f.prxu.org`, etc) in the feed token.  Otherwise looks good - just some questions.

Does feel like the `AppleCredential` model will change/replace some things in here.  But I'd be fine with merging this first, then fixing that up.

2022-12-14 21:26 UTC, cavis commented on app/models/apple/podcast_container.rb
> +      join_on_apple_episode_id(episodes_to_create, new_containers_response).map do |ep, row|
Why the map?  It seems like you're returning `episodes_to_create` after this.

2022-12-14 21:26 UTC, cavis commented on app/models/apple/show.rb
> +    attr_reader :public_feed,
Could also change this to have `:apple_credential` instead, and pull the public/private feed from that?

But this also works.  And is maybe cleaner to test.

2022-12-14 21:26 UTC, cavis commented on app/models/episode.rb
> +    categories_include?([APPLE_FREEMIUM_TAG, APPLE_ONLY_TAG].freeze)
Maybe I already asked this ... but I'm still not entirely clear why we need these hardcoded "apple" tags?

Doesn't the `apple_credential.public_feed.filtered_episodes` and `apple_credential.private_feed.filtered_episodes` already tell us what content to send to apple?

2022-12-14 21:26 UTC, cavis commented on app/models/feed_token.rb
> +      sub("f.prxu.org", "p.prxu.org")
I don't think this is necessary?

The `feed.published_url` already checks if it's `private?` - and varies the host to `ENV['FEEDER_CDN_PRIVATE_HOST']` if needed.

2022-12-20 17:20 UTC, merged

2023-01-03 16:12 UTC, svevang commented
@cavis Moved the feedback over here: https://github.com/PRX/feeder.prx.org/pull/488