Feat/apple api integration
PRX/feeder.prx.org pull request #492
Opened 2023-01-03 15:42 UTC by svevang

2023-01-05 19:59 UTC, svevang commented on app/models/apple/publisher.rb
> +          private_feed: apple_credential.private_feed)
Here's where the apple creds split up the feeds.

2023-01-05 19:59 UTC, svevang commented on app/models/apple/podcast_delivery.rb
> +      results = get_podcast_deliveries_via_containers(api, podcast_containers)
Most of the models follow this pattern for updating existing state:

1) Use the parent model to query for children
2) Reformat the results by querying the main api endpoint for the child model.

2023-01-05 19:59 UTC, svevang commented on app/jobs/publish_feed_job.rb
> +    publish_apple(feed)
The hook into the publishing pipeline.

This method call does nothing unless the apple credentials are set up for the feed in question. And this feed must be on the "public" feed on the credentials.

2023-01-05 21:55 UTC, svevang commented on app/models/apple/episode.rb
> +      feeder_episode.enclosure_url
Since we're hitting the Dovetail CDN, this should include `?noImp`

2023-01-09 18:43 UTC, svevang commented on app/models/apple/episode.rb
> +      feeder_episode.item_guid
The item guid here should work, but it's probably better to use an unchanging / unmapped regular guid here

2023-01-09 22:11 UTC, cavis requested changes
Breezed over some of the `app/models/apple/***` stuff that past-Ryan had looked at.  All looks good to me except that Feed representer change, which I think you'd already realized.

2023-01-09 22:11 UTC, cavis commented on app/models/apple_credential.rb
> +class AppleCredential < ApplicationRecord
Hindsight:

Should this have been `app/models/apple/credential`?

2023-01-09 22:11 UTC, cavis commented on test/representers/api/auth/feed_representer_test.rb
> +    _(json['_links']['prx:private-feed']['href']).must_equal "#{feed.published_url}{?auth}"
Yeah, digging down a bit, it looks like i made `feeds.private` default to `true` in the db.  So this href is now something like `https://p.prxu.org/jjgo/myfeed5/feed-rss.xml{?auth}{?auth}` in this test.

2023-01-13 17:19 UTC, cavis commented on app/models/episode.rb
> +  def categories_include?(match_tags)
Isn't this all duplicative of the Feed?

2023-01-13 17:19 UTC, cavis commented on app/models/apple/episode.rb
> +      decoded_query = URI.decode_www_form(url.query.to_s) << ['noImp', '1']
Ah, ye olde `?noImp`.

Alternatively, could we set a bot-ish UA when making requests to Dovetail?  That's probably a good idea anyways, so we can tell where traffic is coming from.  And there's prior art for that in the podcast world (bots/scrapers like the Spotify one).

Then we can mark the UA as a "bot" in prx-podagent.  And get `is_duplicate=true` records in BQ, so we can debug what's going out to Apple.

2023-01-17 18:12 UTC, cavis approved these changes
Couple unused methods (I think?) ... but otherwise that's everything.

Looks good to me!

2023-01-17 18:12 UTC, cavis commented on app/models/apple/api.rb
> +      req['User-Agent'] = "PRX-Feeder-Apple/1.0 (Rails-#{Rails.env})"
Oh interesting - I guess I thought the api-bridge-lambda would GET the enclosure from DTR (the redirect), download from the dovetail CDN, then upload it to Apple.  But I guess it's Feeder (rails) doing the downloading?

In any case, it's a good idea to set a user-agent.

2023-01-17 18:12 UTC, cavis commented on app/models/episode.rb
> +  def categories_include?(match_tags)
I think this and `normalize_category` are unused in this class now.

2023-01-20 20:30 UTC, merged